<?php
/**
 * 车辆管理 服务
 * User: long
 * Date: 2019/12/30
 * Time: 14:00
 */

namespace App\Services\Driver;


use App\Exceptions\BusinessLogicException;
use App\Http\Resources\CarResource;
use App\Models\Car;
use App\Services\BaseConstService;
use App\Services\BaseService;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class CarService extends BaseService
{
    public function __construct(Car $car)
    {
        parent::__construct($car, CarResource::class);
    }

    public function getPageList()
    {
        $carIdList = DB::table('tour')
            ->where('company_id', auth()->user()->company_id)
            ->where('driver_id', '<>', null)
            ->where('execution_date', Carbon::today()->format('Y-m-d'))
            ->where('status', '<>', BaseConstService::TOUR_STATUS_5)
            ->pluck('car_id')->toArray();
        $this->query->where('is_locked', '=', BaseConstService::DRIVER_TO_NORMAL)->whereNotIn('id',$carIdList);
        return parent::getPageList(); // TODO: Change the autogenerated stub
    }
}
