<?php
/**
 * Created by NLE.TECH INC.
 * User : Crazy_Ning
 * Date : 3/12/2021
 * Time : 4:50 PM
 * Email: nzl9851@88.com
 * Blog : nizer.in
 * FileName: CarMaintainService.php
 */


namespace App\Services\Admin;

use App\Http\Resources\Api\Admin\CarMaintainResource;
use App\Models\CarMaintain;

/**
 * Class CarMaintainService
 * @package App\Services\Admin
 */
class CarMaintainService extends BaseService
{
    /**
     * @var array
     */
    public $filterRules = [
        'car_no' => ['=', 'car_no'],
        'maintain_type' => ['=', 'maintain_type'],
        'is_ticket' => ['=', 'maintain_type'],
        'maintain_factory' => ['=', 'maintain_type'],
        'maintain_date' => ['between', ['begin_date', 'end_date']],
    ];

    /**
     * CarMaintainService constructor.
     * @param  CarMaintain  $model
     */
    public function __construct(CarMaintain $model)
    {
        parent::__construct($model, CarMaintainResource::class);
    }

    /**
     * @param $data
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model
     * @throws \App\Exceptions\BusinessLogicException
     */
    public function create($data)
    {
        $data['maintain_no'] = $this->getOrderNoRuleService()->createCarMaintainNO();

        foreach ($data['maintain_detail'] as $k => $v) {
            $v['maintain_no'] = $data['maintain_no'];
            $this->getCarMaintainDetailService()->create($v);
        }

        return parent::create($data);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getPageList()
    {
        return parent::getPageList(); // TODO: Change the autogenerated stub
    }
}
